### PR TITLE
Create Issue Forms (#159)

### LINKED ISSUE #159: [FEAT] issue template to new issue-forms
Github provides the new feature to use Issue-Forms instead of a Markdown template.

Maybe switching to a Form brings advantages as there are checkboxes, requried files, etc... see [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #159 

Transformed the current template to a Issue-Form.
If you have suggestions feel free to reach out to me

Greetz

Cahllagerfeld 😄 

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/contribute.dev/pull/160"></a>

### CODE REVIEW

**Review by nisarhassan12 — APPROVED** [review]
Thanks for the PR @Cahllagerfeld and sorry for the late review. It LGTM 👍🏿

**Comment by Cahllagerfeld** [comment]
Awesome 😄

**Comment by gtsiolis** [comment]
Thanks for giving this a spin @Cahllagerfeld! 🌟

**Comment by Cahllagerfeld** [comment]
You're welcome @gtsiolis :D

**Pull request merged**
