### PR TITLE
Add 404 page.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes gitpod-io/contribute.dev#45

This is what it looks like:

image

### CODE REVIEW

**Comment by ChristinFrohne** [comment]
This is btw how it looks in Chrome. The alignment shifted
Bildschirmfoto 2020-01-17 um 15 00 45

**Comment by nisarhassan12** [comment]
I have updated the PR @ChristinFrohne Please have a look again.

**Comment by ChristinFrohne** [comment]
It's better but the text is still not aligned to the image. Also, the image could be a bit bigger.
Do you disagree with using the usual button style?  This is how it looks:
Bildschirmfoto 2020-01-20 um 08 15 40

**Comment by nisarhassan12** [comment]
Whoops! Sorry! I have the button text now and made this image bigger This is what it looks like to me. I think it will look a bit different to you because I suspect you are using a big monitor.

image

**Pull request merged**
